#!/bin/bash

SOURCES_PATH="/usr/local/share"

MAKEFILE_PATH="$SOURCES_PATH/newClassGenerator"

make -C "$MAKEFILE_PATH" -f "$MAKEFILE_PATH/Makefile"
cd "$MAKEFILE_PATH"
./a.out "$1" "$2"
mv "$SOURCES_PATH/newClassGenerator/output"/* "$OLDPWD/"
if [ $? -eq 0 ]; then
	echo "File(s) successfully added to current directory"
else
	echo "ERROR"
fi
#make fclean -C "$MAKEFILE_PATH" -f "$MAKEFILE_PATH/Makefile"
