NAME	= a.tmp
CPP		= c++
FLAGS	= -Wall -Wextra -Werror -std=c++98
SRCDIR	= .
OBJDIR	= objs
SRCS	= $(wildcard $(SRCDIR)/*.cpp)
HEADERS = $(wildcard $(SRCDIR)/*.hpp)
OBJS	= $(patsubst $(SRCDIR)/%.cpp,$(OBJDIR)/%.o,$(SRCS))

all: ${NAME}

$(OBJDIR)/%.o: $(SRCDIR)/%.cpp $(HEADERS)
	@mkdir -p $(OBJDIR)
	$(CPP) $(FLAGS) -c $< -o $@

${NAME}: ${OBJS}
	$(CPP) $(FLAGS) ${OBJS} -o $@

clean:
	@rm -rf ${OBJDIR}		

fclean: clean
	@rm -f ${NAME}

re: fclean ${NAME}

.PHONY: all clean fclean re